name: WASM GH Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.14.0
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.5
          actions-cache-folder: 'emsdk-cache'
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.40.0
      - name: Install Wayland deps
        run: sudo apt-get update && sudo apt-get install -y libwayland-dev wayland-protocols
      - run: just build-wasm
        env:
          EMSDK_PATH: ${{ github.workspace }}/emsdk-cache/emsdk-main
      - uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/htmlout/

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment

